const orderViewModel = {
    accordion: {
        order_details: {
            name: 'Order Details',
            tag: 'order_details_accordion',
            id: 'order_details_accordion',
            isOpened: true,
        },
        attached_documents: {
            name: 'Attached Documents',
            tag: 'attached_documents_accordion',
            id: 'attached_documents_accordion',
            isOpened: false,
        },
        order_comments: {
            name: 'Order Comments',
            tag: 'order_comments_accordion',
            id: 'order_comments_accordion',
            isOpened: false,
        },
    },
    form: {
        inputs: {
            sponsor_id: {
                label: 'Sponsor ID',
                name: 'sponsor_id',
                required: true,
                placeholder: 'Sponsor ID...',
                disabled:false,
                value: '',
            },
            delivery_date: {
                label: 'Delivery Date/Time',
                name: 'delivery_date',
                required: true,
                disabled: false,
                value: '',
            },
            delivery_time: {
                name: 'delivery_time',
                required: true,
                disabled: false,
                value: '',
            },
            target_cmo_id: {
                label: 'Target CMO ID',
                name: 'target_cmo_id',
                placeholder: 'Select Target CMO ID...',
                required: true,
                disabled:false,
                options: [
                    {label: 'ID 1', value: '1'},
                    {label: 'ID 2', value: '2'},
                    {label: 'ID 3', value: '3'},
                ],
            },
            study_id: {
                label: 'Study ID',
                name: 'study_id',
                required: true,
                placeholder: 'e.g ABC123X56789',
                disabled:false,
                value: '',
            },
            order_id: {
                label: 'Order ID',
                name: 'order_id',
                required: true,
                placeholder: 'e.g O-000001234',
                disabled:false,
                value: '',
            },
            kit_id_list: {
                label: 'Kit ID List (csv)',
                name: 'kit_id_list',
                required: true,
                placeholder: 'No File',
                disabled:false,
                value: '',
            },
            site_id: {
                label: 'Site ID',
                name: 'site_id',
                placeholder: 'Select Site ID...',
                required: true,
                disabled:false,
                options: [
                    {label: 'Site ID 1', value: '1'},
                    {label: 'Site ID 2', value: '2'},
                    {label: 'Site ID 3', value: '3'},
                ],
            },
            site_region_id: {
                label: 'Site Region ID (Autofilled)',
                name: 'site_region_id',
                required: true,
                placeholder: '',
                disabled:false,
                value: '',
            },
            site_country: {
                label: 'Site Country (Autofilled)',
                name: 'site_country',
                required: true,
                placeholder: '',
                disabled:false,
                value: '',
            },
            temperature_comments: {
                label: 'Temperature Comments',
                name: 'temperature_comments',
                required: true,
                placeholder: 'e.g Do not freeze',
                disabled:false,
                value: '',
            },
            keep_between_temperature_min: {
                label: 'Min Temperature (°C)',
                name: 'keep_between_temperature_min',
                required: true,
                placeholder: '',
                disabled:false,
                value: '',
            },
            keep_between_temperature_max: {
                    label: 'Max Temperature (°C)',
                    name: 'keep_between_temperature_max',
                    required: true,
                    placeholder: '',
                    disabled:false,
                    value: '',
            },
            add_comment: {
                label: 'Add a Comment',
                name: 'add_comment',
                required: true,
                placeholder: 'Add a comment....',
                disabled:false,
                value: '',
            },
        },
        docs: {},
        attachment: {
            label: 'Select files',

            listFiles: true,
            filesAppend: false,
            files: [],
        },
        documents: [],
        comments: [],
    },

}

module.exports = orderViewModel;
